<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CommunicationKernel.Core.Transport</AssemblyName>
    <RootNamespace>CommunicationKernel.Core.Transport</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationKernel.Core.Abstractions\CommunicationKernel.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
