<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationKernel.Core.Abstractions\CommunicationKernel.Core.Abstractions.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Communication.Transport\CommunicationKernel.Communication.Transport.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Communication.Protocol\CommunicationKernel.Communication.Protocol.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugin.Runtime\CommunicationKernel.Plugin.Runtime.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Engine.Router\CommunicationKernel.Engine.Router.csproj" />
    <ProjectReference Include="..\CommunicationKernel.EngineHost\CommunicationKernel.Engine.Host.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Modbus.Core\CommunicationKernel.Plugins.Modbus.Core.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Modbus.Tcp\CommunicationKernel.Plugins.Modbus.Tcp.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Modbus.Rtu\CommunicationKernel.Plugins.Modbus.Rtu.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Modbus.Ascii\CommunicationKernel.Plugins.Modbus.Ascii.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Panasonic.MewtocolTcp\CommunicationKernel.Plugins.Panasonic.MewtocolTcp.csproj" />
    <ProjectReference Include="..\CommunicationKernel.Plugins.Siemens.S7\CommunicationKernel.Plugins.Siemens.S7.csproj" />
  </ItemGroup>

</Project>
